BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "notify" (
	"id"	INTEGER NOT NULL UNIQUE,
	"message"	TEXT NOT NULL,
	"date"	TEXT NOT NULL,
	"time"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "notify" VALUES (1,'ส่งงาน','2023-12-05','09:00:00');
COMMIT;
